dajor:
  name: Daniel 
  description: Creator
  avatar: https://avatars.githubusercontent.com/u/922524

FellowFellow:
  name: Benedikt ( Ben )
  description: Fellow Developer
  avatar: https://avatars.githubusercontent.com/u/74979180

amnai2p:
  name: Amna
  description: Frontend
  avatar: https://avatars.githubusercontent.com/u/42763988

masadusman:
  name: Asad 
  description: Backend
  avatar: https://avatars.githubusercontent.com/u/83513548

amierhaider:
  name: Amier  
  description: Backend
  avatar: https://avatars.githubusercontent.com/u/2101825

WingsOfCobra:
  name: Anian 
  description: Fellow
  avatar: https://avatars.githubusercontent.com/u/49494079
Bennse666:
  name: Benjamin 
  description: Fellow
  avatar: https://avatars.githubusercontent.com/u/62914265

shehryar-azam:
  name: Shehryar
  description: Frontend
  avatar: https://avatars.githubusercontent.com/u/57675151