site_name: Polydocs Dokumentation
site_url: https://docs.polydocs.io
site_author: Daniel Jordan
site_description: Auf diesen Seiten erfahren Sie viel über unsere verschiedenen Softwarelösungen, die Sie bei der Digitalisierung und der digitalen Transformation in Ihrem Unternehmen unterstützen.
theme:
  name: material
  custom_dir: overrides
  #favicon: _images/polydocs_Logo.svg
  favicon: _images/polydocs_Icon.svg
  font:
    text: Open Sans
  language: en
  logo: _images/polydocs_Icon.svg
  palette:
      scheme: light
      primary: indigo
  features:
    - navigation.instant
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/?h=navigation+tabs#navigation-tabs
    - navigation.tabs
    - navigation.tabs.sticky
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/?h=navigation+tabs#anchor-tracking
    - navigation.tracking
    - navigation.indexes
# https://squidfunk.github.io/mkdocs-material/customization/?h=#additional-css
extra_css:
  - _extra/css/extra.css
# https://squidfunk.github.io/mkdocs-material/customization/?h=#additional-javascript
extra_javascript:
  - _extra/javascript/extra.js
extra:
  alternate:
    - name: English
      link: /
      lang: en
    - name: Deutsch
      link: /de/
      lang: de
  consent:
    title: Cookie consent
    description: >-
      Wir verwenden Cookies, um Ihre wiederholten Besuche und Präferenzen zu erkennen, sowie
      und um die Effektivität unserer Dokumentation zu messen und um festzustellen, ob die Nutzer
      finden, wonach sie suchen. Mit Ihrer Zustimmung helfen Sie uns, unsere
      unsere Dokumentation zu verbessern.
  generator: false
  copyright: Copyright &copy; 2022 Polydocs GmbH
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/645725/
  analytics:
    provider: google
    property: UA-208531131-1
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Vielen Dank für Ihr Feedback!
        - icon: material/emoticon-sad-outline
          name: Diese Seite könnte verbessert werden
          data: 0
          note: >-
            Vielen Dank für Ihr Feedback! Helfen Sie uns, diese Seite zu verbessern, indem Sie unser Feedback-Formular <a href="https://docs.google.com/forms/d/e/1FAIpQLScEh_N3lX4JFfvE1fdtImtSv2eVjcEGjlPzsH5usNfN4uNOIg/viewform?usp=pp_url&entry.1764397339=[Feedback]+{title}+-+{url}" target=_blank>nutzen</a>.
markdown_extensions:
  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/?h=attr#attribute-lists attr_list is required for several other features. Always enable.
  - attr_list
  # https://squidfunk.github.io/mkdocs-material/reference/admonitions/?h=admoni
  - admonition
  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#superfences Superfences is required for several other features. Always enable.
  - pymdownx.superfences
  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#superfences Used for tags, setting unique templates for certain pages, and other custom frontmatter.
  - meta
  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#highlight
  - pymdownx.highlight:
      linenums: true
  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#inlinehilite
  - pymdownx.inlinehilite
  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#snippets
  - pymdownx.snippets
  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#tabbed
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  # https://www.mkdocs.org/user-guide/writing-your-docs/#linking-to-pages
  - toc:
      permalink: "#"
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
plugins:
  - search
  - literate-nav
  - tags:
      tags_file: tags.md
nav:
  - Changelog: Release/Release_notes.md
  - DOC²:
    - Erste Schritte: doc2/index.md
    - Datensicherheit: security/datensicherung.md
    - OnBoarding: doc2/onboarding.md
    - Einrichtung: doc2/deployment.md
    - Dashboard:
      - doc2/dashboard/index.md
      - Manueller Import: doc2/manual-import.md
      - Tastatur: doc2/keyboard.md
      - Dokumentstatus: doc2/document_status.md
    - Dokumentenvalidierung:
      - doc2/document-validation/index.md
      - Stammdatenabfrage: doc2/document-validation/master-data-validation.md
      - OCR-Ansicht: doc2/document-validation/ocr-view.md
      - AI-Indikator: doc2/document-validation/ai-indicator.md
      # - Expressions: doc2/document-validation/exception-filters.md
    - Tabellenextraktion:
      - doc2/table-extraction/index.md
      - Training der Tabellenextraktion: doc2/table-extraction/training-of-table-extraction.md
      - Tabellen und Spalten definieren: doc2/table-extraction/define-table-and-columns.md
      - Neue Spalte hinzufügen: doc2/table-extraction/add-new-table-column.md
      - Zuordnung von Spalten: doc2/table-extraction/mapping-of-columns.md
      - Group function: doc2/table-extraction/group-function.md
      - Manuelle Zeilenauswahl: doc2/table-extraction/manual-row-selection.md
      - Erweiterte Einstellungen: doc2/table-extraction/advanced-settings.md
      - Regeln speichern und löschen: doc2/table-extraction/save-rules-and-delete-rules.md

    - DOC² mit Infor:
      - doc2/doc2-with-infor/index.md
      - Infor Infrastruktur: doc2/doc2-with-infor/infrastructure.md
      - Anwendungsbeispiele: doc2/doc2-with-infor/infor.md
      - Diagramm: doc2/doc2-with-infor/inforflow.md
      - Integration mit Infor IDM and ERP:
        - doc2/doc2-with-infor/IDM-business-context-model.md
      - Infor SSO: doc2/doc2-with-infor/configuring-sso-in-cloud.md
    # - DOC² with Workflow²: doc2/workflow.md
    - Einstellungen:
      - doc2/settings/index.md
      - Untertnehmensinformationen: doc2/company-information.md
      - Gruppen, Benutzer und Berechtigungen:
        - doc2/settings/groups-users-permissons/index.md
        - Benutzer: doc2/settings-users.md
      - Integration:
        - doc2/settings/integration/index.md
        - API: doc2/settings/integration/api-integration.md
        - Beispiele für API-Aufrufe: doc2/settings/integration/api-calls-examples.md
        - SSO Einstellungen: doc2/settings-sso-settings.md
      - Dokumententypen: doc2/settings-document-types.md
      - E-Mail Benachrichtigung: doc2/settings/email-notification.md
      - Module:
        - doc2/modules/index.md
        - Zugriff auf Module: doc2/modules/modules-overview.md
        - Genehmigung: doc2/modules/approval.md
        - Layout-Ersteller: doc2/modules/layout-builder.md
        # - Modelle und Etiketten: doc2/modules/models-and-labels.md
        - Doc Script: doc2/modules/doc-script.md
        - Doc Scan: doc2/modules/doc-scan.md
      - Alle Importoptionen:
        - doc2/import/index.md
        - E-Mail: doc2/e-mail.md
        - Fileshare-Import:
          - doc2/fileshare/index.md
          - Windows: doc2/fileshare/watchdog-windows.md
          # - macOS: doc2/fileshare/watchdog-macOS.md
        - Webhook: doc2/api.md
      - Alle Exportoption:
        - doc2/export/index.md
        - Export nach Infor:
          - doc2/export/export-to-infor/index.md
          - Export nach Infor ION and IDM: doc2/export/infor-ion.md
          - So erstellen Sie eine BOD-Mapping-Datei: doc2/export/how-to-create-a-bod-mapping-file.md
          - So erstellen Sie eine IDM-Mapping-Datei: doc2/export/how-to-create-a-idm-mapping-file.md
          - Export nach Infor IDM: doc2/export/infor-idm.md
          - Infor ION API-Datei: doc2/export/create-a-infor-ion-api-file.md
          - Export nach Infor ION und IDM: doc2/export/infor-ion.md
        - Webhook: doc2/export/webhook.md
        - XML-Export: doc2/export/xml-export.md
        - Exportieren nach Flow²: doc2/export/export-to-flow2.md


      - Beträge: doc2/settings-amount-settings.md
      - Lieferantenvalidierung: doc2/settings-master-data-validation.md
    - PO-Matching:
      - doc2/pomatching/po-matching/index.md
      - Rechnung: doc2/pomatching/po-matching-invoices.md
      - Lieferschein: doc2/pomatching/po-matching-delivery-notes.md
      - Auftragsbestätigung: doc2/pomatching/po-matching-order-confirmation.md

    - ZUGFeRD: doc2/zugpferd.md

    - Gruppen & Privilegien: security/privileges.md
    - Admin-Leitfäden: doc2/admin-guides/postman-projects.md
    - SSO:
      - doc2/SSO/index.md
      - SSO für Azure AD mit DOC²: doc2/SSO/SSO-for-Azure-AD.md
  - FLOW²:
    - Einführung: flow2/index.md
    - Erste Schritte: flow2/introduction.md
    - Onboarding: flow2/flow2-onboarding-guide.md
    - Einrichtung: flow2/deployment.md
    - Benutzer-Dashboard: flow2/home.md
    - Systemkonfiguration: flow2/settings-system-setup.md
    - Metadaten: flow2/metadata.md
    - Import aus DOC²: flow2/import-from-doc2.md
  - KV²:
    - Erste Schritte: kv2/getting-started.md
    - Installation: kv2/installation.md
    - Tutorial: kv2/kv2-tutorial.md
    - How To:
      - Training KV² für Tabellenextraktion: kv2/training-kv2-for-table-extraction.md
      - Unterschiedliche Steuerbeträge: kv2/how-to-deal-with-different-vat-amounts.md
      - Alle extrahierten Felder: kv2/all-extracted-fields.md
      - Regeln: kv2/how-to-delete-a-kv2-plugin-rule-from-the-database.md
    - Ephesoft neu starten:
      - Cloud: kv2/restart-ephesoft-on-cloud.md
      - OnPremise: kv2/restart-ephesoft-on-premise.md
    - Einschränkungen: kv2/limitations-for-fellow-kv2-plugin.md
    - Feedback Funktion: kv2/enable-feedback-function.md
  - TE²:
    - Erste Schritte: te2/fellow-te2-plugin.md
    - Installation: te2/install.md
    - Tutorial: te2/fellowte2-tutorial.md
    - Ephesoft Externe Anwendung: te2/ephesoft-external-application.md
    - Infor LN BOD Mapping: te2/ln_bodmapping.md
    - Feedback Funktion: te2/enable-feedback-function.md
  - OCR²:
    - Überblick: ocr/overview.md
    - Installation & Konfiguration: ocr/installation-config.md
    - GErste Schritte: ocr/get-started.md
    - OCR-Serverprozess: ocr/ocrserverprocess.md
    - Innenseiten erkennen: ocr/detect-inside-pages.md
    - PDF zusammenführen/aufteilen: ocr/merge-split-pdf.md
    - API: ocr/ocr-api.md
  # - Insight²:
  #   - Introduction: insight2/index.md
  #   - Deployment: insight2/deployment.md
  #   - Security: insight2/security.md
  #   - Tracking: insight2/tracking.md
  #   - Getting Started:
  #     - insight2/tutorial/index.md
  #     - Adding datasource: insight2/tutorial/adding-a-datasource.md
  #     - Adding widget: insight2/tutorial/adding-widget.md
  #     - Building Queries: insight2/tutorial/building-queries.md
  #     - Creating new app: insight2/tutorial/creating-app.md
  #     - Debugger: insight2/tutorial/debugger.md
  #     - Manage User Groups: insight2/tutorial/manage-users-groups.md
  #     - Mobile Layout: insight2/tutorial/mobile-layout.md
  #     - Preview and Sharing Apps: insight2/tutorial/sharing-and-deploying.md
  #     - Transformations: insight2/tutorial/transformations.md
  #     - Versioning and release: insight2/tutorial/versioning-and-release.md
  #     - Keyboard Shortcuts: insight2/tutorial/keyboard-shortcuts.md
  #     - Multi-Workspace: insight2/tutorial/multiworkspace.md
  #   - IN² Examples:
  #     - insight2/examples/index.md
  #     - Change text color in columns of the table: insight2/how-to/access-cellvalue-rowdata.md
  #     - Bulk update multiple rows in table: insight2/how-to/bulk-update-multiple-rows-in-table.md
  #     - REST API authentication using OAuth 2.0: insight2/how-to/oauth2-authorization.md
  #     - Upload files on AWS S3 bucket: insight2/how-to/upload-files-aws.md
  #     - Upload files using GCS: insight2/how-to/upload-files-gcs.md
  #   - Actions:
  #     - insight2/actions/actions/index.md
  #     - Generate file: insight2/actions/generate-file.md
  #     - Set localStorage: insight2/actions/set-localstorage.md
  #   - Data-Sources:
  #     - Overview: insight2/data-sources/index.md
  #     - Airtable: insight2/data-sources/airtable.md
  #     - Appwrite: insight2/data-sources/appwrite.md
  #     - Athena: insight2/data-sources/athena.md
  #     - Baserow: insight2/data-sources/baserow.md
  #     - BigQuery: insight2/data-sources/bigquery.md
  #     - CouchDB: insight2/data-sources/couchdb.md
  #     - Custom JS: insight2/data-sources/custom-js.md
  #     - DynamoDB: insight2/data-sources/dynamodb.md
  #     - Elasticsearch: insight2/data-sources/elasticsearch.md
  #     - Firestore: insight2/data-sources/firestore.md
  #     - GCS: insight2/data-sources/gcs.md
  #     - Google Sheets: insight2/data-sources/google.sheets.md
  #     - GraphQL: insight2/data-sources/graphql.md
  #     - InfluxDB: insight2/data-sources/influxdb.md
  #     - Mailgun: insight2/data-sources/mailgun.md
  #     - MinIO: insight2/data-sources/minio.md
  #     - MongoDB: insight2/data-sources/mongodb.md
  #     - MSSQL: insight2/data-sources/mssql.md
  #     - MySQL: insight2/data-sources/mysql.md
  #     - WF²: insight2/data-sources/WF².md
  #     - Notion: insight2/data-sources/notion.md
  #     - OpenAPI: insight2/data-sources/openapi.md
  #     - OracleDB: insight2/data-sources/oracledb.md
  #     - PostgreSQL: insight2/data-sources/postgresql.md
  #     - Redis: insight2/data-sources/redis.md
  #     - REST API: insight2/data-sources/restapi.md
  #     - RethinkDB: insight2/data-sources/rethinkdb.md
  #     - S3: insight2/data-sources/s3.md
  #     - SAP HANA: insight2/data-sources/saphana.md
  #     - SendGrid: insight2/data-sources/sendgrid.md
  #     - SMTP: insight2/data-sources/smtp.md
  #     - Snowflake: insight2/data-sources/snowflake.md
  #     - Typesense: insight2/data-sources/typesense.md
  #     - WooCommerce: insight2/data-sources/woocommerce.md
  #   - Widgets:
  #     - Overview: insight2/widgets/index.md
  #     - Button group: insight2/widgets/button-group.md
  #     - Button: insight2/widgets/button.md
  #     - Calendar: insight2/widgets/calendar.md
  #     - Chart: insight2/widgets/chart.md
  #     - Checkbox: insight2/widgets/checkbox.md
  #     - Circular Progress Bar: insight2/widgets/circular-progress-bar.md
  #     - Code Editor: insight2/widgets/code-editor.md
  #     - Container: insight2/widgets/container.md
  #     - Custom Component: insight2/widgets/custom-component.md
  #     - Date Range Picker: insight2/widgets/date-range-picker.md
  #     - Datepicker: insight2/widgets/datepicker.md
  #     - Divider: insight2/widgets/divider.md
  #     - Dropdown: insight2/widgets/dropdown.md
  #     - File picker: insight2/widgets/file-picker.md
  #     - iFrame: insight2/widgets/iframe.md
  #     - Image: insight2/widgets/image.md
  #     - Kanban: insight2/widgets/kanban.md
  #     - Listview: insight2/widgets/listview.md
  #     - Map: insight2/widgets/map.md
  #     - Modal: insight2/widgets/modal.md
  #     - Multiselect: insight2/widgets/multiselect.md
  #     - Number input: insight2/widgets/number-input.md
  #     - Password input: insight2/widgets/password-input.md
  #     - PDF: insight2/widgets/pdf.md
  #     - QR-Scanner: insight2/widgets/qr-scanner.md
  #     - Radio button: insight2/widgets/radio-button.md
  #     - Range Slider: insight2/widgets/range-slider.md
  #     - Rich Text Editor: insight2/widgets/rich-text-editor.md
  #     - Spinner: insight2/widgets/spinner.md
  #     - Star: insight2/widgets/star.md
  #     - Statistics: insight2/widgets/statistics.md
  #     - Steps: insight2/widgets/steps.md
  #     - Table: insight2/widgets/table.md
  #     - Tabs: insight2/widgets/tabs.md
  #     - Tags: insight2/widgets/tags.md
  #     - Text input: insight2/widgets/text-input.md
  #     - Text: insight2/widgets/text.md
  #     - Textarea: insight2/widgets/textarea.md
  #     - Timeline: insight2/widgets/timeline.md
  #     - Timer: insight2/widgets/timer.md
  #     - Toggle Switch: insight2/widgets/toggle-switch.md


