[build]
  command = "pip install --upgrade pip && pip install git+https://${GH_TOKEN}@github.com/squidfunk/mkdocs-material-insiders.git && mkdocs build -f config/en/mkdocs.yml"
  publish = "generated/en"
