site_name: FELLOWPRO Dokumentation
docs_dir: '../../docs/de'                           # Where to find the English markdown files
site_dir: '../../generated/de'                      # Where to put the English HTML files
site_url: https://de.docs.fellowpro.com
site_author: Daniel Jordan
site_description: Auf diesen Seiten erfahren Sie viel über unsere verschiedenen Softwarelösungen, die Sie bei der Digitalisierung und der digitalen Transformation in Ihrem Unternehmen unterstützen.
theme:
  name: material
  logo: _images/LOGO.svg
  favicon: _images/LOGO.svg
  font:
    text: Montserrat
  language: de
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

  palette:
    - scheme: default
      primary: custom
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: In den dunkeln Modus wechseln
    - scheme: slate
      primary: custom
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: In den hellen Modus wechseln

extra_css:
  - _extra/css/extra.css
# https://squidfunk.github.io/mkdocs-material/customization/?h=#additional-javascript
extra_javascript:
  - _extra/javascript/extra.js

extra:
  alternate:
    - name: English
      link: https://en.docs.fellowpro.com
      lang: en
    - name: Deutsch
      link: https://de.docs.fellowpro.com
      lang: de
  consent:
    title: Cookie consent
    description: >-
      Wir verwenden Cookies, um Ihre wiederholten Besuche und Präferenzen zu erkennen, sowie
      und um die Effektivität unserer Dokumentation zu messen und um festzustellen, ob die
      finden, wonach sie suchen. Mit Ihrer Zustimmung helfen Sie uns, unsere
      unsere Dokumentation zu verbessern.
  annotate:
    json: [.s2]
  generator: false
  copyright: Copyright &copy; 2023 FellowPRO AG
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/645725/
  analytics:
    provider: google
    property: UA-208531131-1
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by
            using our <a href="https://docs.google.com/forms/d/e/1FAIpQLScEh_N3lX4JFfvE1fdtImtSv2eVjcEGjlPzsH5usNfN4uNOIg/viewform?usp=pp_url&entry.1764397339=[Feedback]+{title}+-+{url}" target=_blank>feedback form</a>.


markdown_extensions:
  
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - tables
  
plugins:
  - search:
      lang: de
  - literate-nav
  - git-revision-date-localized:
      type: date
      fallback_to_build_date: true
  - git-authors
  - tags:
      tags_file: tags.md
  - minify:
      minify_html: true



nav:
  - Changelog: Release/Release_notes.md
  - DOC²:
    - Einstieg: doc2/index.md
    - Datensicherheit: security/datensicherung.md
    - OnBoarding: doc2/onboarding.md
    - Bereitstellung: doc2/deployment.md
    - Dashboard:
      - doc2/dashboard/index.md
      - Manueller Import: doc2/manual-import.md
      - Tastenkombinationen: doc2/keyboard.md
      - Dokumentenstatus: doc2/document_status.md
    - Dokumentenvalidierung:
      - doc2/document-validation/index.md
      - Validierung von Stammdaten: doc2/document-validation/master-data-validation.md
      - OCR-Ansicht: doc2/document-validation/ocr-view.md
      - KI-Indikator: doc2/document-validation/ai-indicator.md
      # - Ausdrücke: doc2/document-validation/exception-filters.md
    - Tabellen auslesen:
      - doc2/table-extraction/index.md
      - Schulung zur Tabellenauswertung: doc2/table-extraction/training-of-table-extraction.md
      - Definition von Tabellen und Spalten: doc2/table-extraction/define-table-and-columns.md
      - Hinzufügen neuer Spalten: doc2/table-extraction/add-new-table-column.md
      - Zuordnung von Spalten: doc2/table-extraction/mapping-of-columns.md
      - Gruppenfunktion: doc2/table-extraction/group-function.md
      - Manuelle Zeilenauswahl: doc2/table-extraction/manual-row-selection.md
      - Erweiterte Einstellungen: doc2/table-extraction/advanced-settings.md
      - Speichern und Löschen von Regeln: doc2/table-extraction/save-rules-and-delete-rules.md

    - DOC² mit Infor:
      - doc2/doc2-with-infor/index.md
      - Infor-Infrastruktur: doc2/doc2-with-infor/infrastructure.md
      - Anwendungsfälle: doc2/doc2-with-infor/infor.md
      - Diagramm: doc2/doc2-with-infor/inforflow.md
      - Integration mit Infor IDM und ERP:
        - doc2/doc2-with-infor/IDM-business-context-model.md
      - Infor SSO: doc2/doc2-with-infor/configuring-sso-in-cloud.md
    # - DOC² with Workflow²: doc2/workflow.md
    - Einstellungen:
      - doc2/settings/index.md
      - Firmeninformationen: doc2/company-information.md
      - Gruppen, Benutzer und Berechtigungen:
        - doc2/settings/groups-users-permissons/index.md
        - Benutzer: doc2/settings-users.md
      - Integration:
        - doc2/settings/integration/index.md
        - API: doc2/settings/integration/api-integration.md
        - Beispiele für API-Aufrufe: doc2/settings/integration/api-calls-examples.md
        - SSO-Einstellungen: doc2/settings-sso-settings.md
      - Dokumenttypen: doc2/settings-document-types.md
      - E-Mail-Benachrichtigungen: doc2/settings/email-notification.md
      - Module: doc2/modules.md
      - Alle Importoptionen:
        - doc2/import/index.md
        - Email: doc2/e-mail.md
        - Fileshare Import:
          - doc2/fileshare/index.md
          - Windows: doc2/fileshare/watchdog-windows.md
          # - macOS: doc2/fileshare/watchdog-macOS.md
        - Webhook: doc2/api.md
      - All Export Options:
        - doc2/export/index.md
        - Export to Infor:
          - doc2/export/export-to-infor/index.md
          - Export to Infor ION and IDM: doc2/export/infor-ion.md
          - How to create a BOD mapping file: doc2/export/how-to-create-a-bod-mapping-file.md
          - How to create a IDM mapping file: doc2/export/how-to-create-a-idm-mapping-file.md
          - Export to Infor IDM: doc2/export/infor-idm.md
          - Infor ION API File: doc2/export/create-a-infor-ion-api-file.md
          - Export to Infor ION and IDM: doc2/export/infor-ion.md
        - Webhook: doc2/export/webhook.md
        - Export to Flow²: doc2/export/export-to-flow2.md


      - Amount: doc2/settings-amount-settings.md
      - Supplier Validation: doc2/settings-master-data-validation.md
    - PO Matching:
      - doc2/pomatching/po-matching/index.md
      - Invoice: doc2/pomatching/po-matching-invoices.md
      - Delivery Note: doc2/pomatching/po-matching-delivery-notes.md
      - Order Confirmation: doc2/pomatching/po-matching-order-confirmation.md

    - ZUGFeRD: doc2/zugpferd.md

    - Groups & Privileges: security/privileges.md
    - Admin-Guides: doc2/admin-guides/postman-projects.md
    - SSO:
      - doc2/SSO/index.md
      - SSO for Azure AD with DOC²: doc2/SSO/SSO-for-Azure-AD.md


  - FLOW²:
    - Einführung: flow2/index.md
    - Getting Started: flow2/introduction.md
    - Onboarding Guide: flow2/flow2-onboarding-guide.md
    - Einführung: flow2/deployment.md
    - Benutzer Dashboard: flow2/home.md
    - System Setup: flow2/settings-system-setup.md
    - Metadata: flow2/metadata.md
    - Import from Doc²: flow2/import-from-doc2.md
  - KV²:
    - Getting Started: kv2/getting-started.md
    - Installation: kv2/installation.md
    - Tutorial: kv2/kv2-tutorial.md
    - How To:
      - Training KV² for Table Extraction: kv2/training-kv2-for-table-extraction.md
      - Different VAT amounts: kv2/how-to-deal-with-different-vat-amounts.md
      - All Extracted Fields: kv2/all-extracted-fields.md
      - Rules: kv2/how-to-delete-a-kv2-plugin-rule-from-the-database.md
    - Restart Ephesoft:
      - Cloud: kv2/restart-ephesoft-on-cloud.md
      - OnPremise: kv2/restart-ephesoft-on-premise.md
    - Einschränkungen: kv2/limitations-for-fellow-kv2-plugin.md
    - Feedback Function: kv2/enable-feedback-function.md
  - TE²:
    - Erste Schritte: te2/fellow-te2-plugin.md
    - Einrichtung: te2/install.md
    - Tutorial: te2/fellowte2-tutorial.md
    - Ephesoft External Application: te2/ephesoft-external-application.md
    - Infor LN BOD Mapping: te2/ln_bodmapping.md
    - Feedback Function: te2/enable-feedback-function.md
  - OCR²:
    - Overview: ocr/overview.md
    - Einrichtung & Config: ocr/installation-config.md
    - Erste Schritte: ocr/get-started.md
    - OCR Server Process: ocr/ocrserverprocess.md
    - Detect inside pages: ocr/detect-inside-pages.md
    - Merge/Split PDF: ocr/merge-split-pdf.md
    - API: ocr/ocr-api.md
  